### ISSUE TITLE
Developmental Game Start Procedure

### ISSUE THREAD

**Issue by ChikkiPikki** [devanujpatel/python_monopoly#8]
Hello Dev
I was trying to view the game, but I don't know where to start it
Could you please tell me?
Thanks

**Comment by devanujpatel** [comment]
Okay. So first I would recommend you to see the 'server' file in the server and client branch. Then move on to client. You can also review both of them simultaneously.If you want to see the game in action then tell me cuz it's a bit long procedure to explain in text.

**Comment by ChikkiPikki** [comment]
Yea, I want to see the game in action, if you feel so

**Comment by ChikkiPikki** [comment]
It is also fine if you send me just snapshots to prevent breaking anything

**Comment by devanujpatel** [comment]
I assume you already have the code ready in your IDE. You will have to run server first then the client. But before doing that change the IP address "192.168.29.201" or 192.168.29.201 to your own computer's up address.  Get your ip address by typing ipconfig in your command prompt.

**Comment by ChikkiPikki** [comment]
Dev, I can do that, but just send me the snaps of the game

**Comment by ChikkiPikki** [comment]
Okay, on it
What should I keep the IP?
My own?

**Comment by devanujpatel** [comment]
Yes!

**Comment by ChikkiPikki** [comment]
Okay, I have changed IPs in both the files, now should I run them?

**Comment by devanujpatel** [comment]
No not yet. I thing u have to do is go to the player class online version line 138 and comment it out ( add # at the start of the line).

**Comment by devanujpatel** [comment]
Then start the game.

**Comment by ChikkiPikki** [comment]
Okay sure

**Comment by ChikkiPikki** [comment]
![Screenshot (1338)](https://user-images.githubusercontent.com/66836432/99142619-be926f00-267c-11eb-8fc3-ae7f0e867f85.png)
I am seeing this, I have done as you have said.
What do you suggest?

**Comment by ChikkiPikki** [comment]
I have tried to change the IP to 0.0.0.0 and the server.py file is working
The client isn't

**Comment by ChikkiPikki** [comment]
Okay wait, I think I should use PyCharm now

**Comment by ChikkiPikki** [comment]
OKAY DEV I GOT IT

**Comment by ChikkiPikki** [comment]
![Screenshot (1340)](https://user-images.githubusercontent.com/66836432/99142953-b851c200-267f-11eb-81b4-5cf53cb9e2b4.png)
Nicely done dev, but how do I roll the dice

**Comment by ChikkiPikki** [comment]
![Screenshot (1341)](https://user-images.githubusercontent.com/66836432/99143047-80974a00-2680-11eb-9396-a9c3ade8f0e8.png)
How do I roll the dice?

**Comment by devanujpatel** [comment]
Sorry I was absent for some time .. it was lunch time. Okay so I see you have two clients and the server running. Now check both of the client windows. You should see a big orange color button. Click it to roll dice .

**Comment by ChikkiPikki** [comment]
Okay just a minute

**Comment by devanujpatel** [comment]
And also plz go to player class online version. Under the def function update position remove the time.sleep comments LINE 51 and 55. Then run as you did before.😃

**Comment by ChikkiPikki** [comment]
Okay sure

**Comment by ChikkiPikki** [comment]
I am clicking it, but it isn't rolling the dice
I have removed the time.sleep comments

**Comment by devanujpatel** [comment]
Is the window becoming unresponsive or something. I run it a thousand times a day to test some new features and it works perfectly.

**Comment by ChikkiPikki** [comment]
Check this error
![Screenshot (1342)](https://user-images.githubusercontent.com/66836432/99143289-5181d800-2682-11eb-9abd-9a17e2a31ec1.png)

**Comment by ChikkiPikki** [comment]
It looks like I have missed chances and then, it isn't working...or have I broken something?
![Screenshot (1343)](https://user-images.githubusercontent.com/66836432/99143359-b50c0580-2682-11eb-8f62-d3bef8ee09ec.png)

**Comment by devanujpatel** [comment]
Oh yeah .. what i did for devopment purpose was that instead of doing a random for dice roll I kept an entry box for entering dice values. This is a bit tricky to revert back to original ..  What u should do is in the text box enter a no. from 1-12. Make sure it is a valid positive python int. . Then click okay.

**Comment by ChikkiPikki** [comment]
Ya I got it

**Comment by ChikkiPikki** [comment]
![Screenshot (1345)](https://user-images.githubusercontent.com/66836432/99143445-8cd0d680-2683-11eb-895a-3560b38e88f2.png)

**Comment by devanujpatel** [comment]
Re run everything and make sure u don't miss chances. It's still in development.

**Comment by ChikkiPikki** [comment]
Nicely done Dev, it feels good

All the best to complete it, let's see who completes first

**Comment by ChikkiPikki** [comment]
And also thanks for your insight and help bro

**Comment by devanujpatel** [comment]
Your welcome and all the best to you too.

**Comment by devanujpatel** [comment]
I see you do not have a repo about you rproj or is it private.

**Comment by devanujpatel** [comment]
And can you explain something more about your project?
